In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score

C:\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
## 设置属性防止中文乱码
mpl.rcParams['font.sans-serif'] = [u'SimHei']
mpl.rcParams['axes.unicode_minus'] = False

In [3]:
## 读取数据
# 'sepal length', 'sepal width', 'petal length', 'petal width'
iris_feature = u'花萼长度', u'花萼宽度', u'花瓣长度', u'花瓣宽度'
path = './datas/iris.data'  
data = pd.read_csv(path, header=None)
x, y = data[range(4)], data[4]
y = pd.Categorical(y).codes
x = x[[0, 1]]

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=28, train_size=0.6)

In [6]:
clf = svm.SVC(C=1, kernel='linear')
clf.fit(x_train, y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [7]:
print clf.score(x_train, y_train) 
print '训练集准确率：', accuracy_score(y_train, clf.predict(x_train))
print clf.score(x_test, y_test)
print '测试集准确率：', accuracy_score(y_test, clf.predict(x_test))
print 'decision_function:\n', clf.decision_function(x_train)
print '\npredict:\n', clf.predict(x_train)

0.822222222222
训练集准确率： 0.822222222222
0.783333333333
测试集准确率： 0.783333333333
decision_function:
[[ -1.39999882e+00  -9.99758749e-01   7.33899720e-01]
 [  1.00001568e+00   7.45207354e-01  -6.06346784e-01]
 [ -1.40000172e+00  -9.43327605e-01   1.00102775e+00]
 [  1.19999393e+00   1.33736775e+00   1.39672959e+00]
 [ -3.19997127e+00  -3.05619598e+00  -1.80036183e+00]
 [  2.20000698e+00   1.92806170e+00   1.92734141e-01]
 [  2.39998814e+00   2.46379095e+00   1.92868249e+00]
 [  1.19999393e+00   1.33736775e+00   1.39672959e+00]
 [ -1.47633540e-05   4.93100274e-01   2.20041686e+00]
 [ -3.59998867e+00  -3.05546276e+00  -1.96825911e-01]
 [  1.19999973e+00   1.22450546e+00   8.62473530e-01]
 [ -1.00000462e+00  -5.49042823e-01   1.26738806e+00]
 [ -1.39999302e+00  -1.11262104e+00   1.99643656e-01]
 [  2.39999393e+00   2.35092866e+00   1.39442642e+00]
 [ -2.39997707e+00  -2.26762642e+00  -1.26764121e+00]
 [ -9.99998817e-01  -6.61905112e-01   7.33131996e-01]
 [  1.40000118e+00   1.36521671e+00   7.2

C:\Anaconda2\lib\site-packages\sklearn\svm\base.py:552: ChangedBehaviorWarning: The decision_function_shape default value will change from 'ovo' to 'ovr' in 0.19. This will change the shape of the decision function returned by SVC.
  "SVC.", ChangedBehaviorWarning)


In [8]:
# 画图
N = 500
x1_min, x2_min = x.min()
x1_max, x2_max = x.max()

t1 = np.linspace(x1_min, x1_max, N)
t2 = np.linspace(x2_min, x2_max, N)
x1, x2 = np.meshgrid(t1, t2)  
grid_show = np.dstack((x1.flat, x2.flat))[0] 

grid_hat = clf.predict(grid_show)       
grid_hat = grid_hat.reshape(x1.shape)  

cm_light = mpl.colors.ListedColormap(['#A0FFA0', '#FFA0A0', '#A0A0FF'])
cm_dark = mpl.colors.ListedColormap(['g', 'r', 'b'])
plt.figure(facecolor='w')
plt.pcolormesh(x1, x2, grid_hat, cmap=cm_light)
plt.scatter(x[0], x[1], c=y, edgecolors='k', s=50, cmap=cm_dark)     
plt.scatter(x_test[0], x_test[1], s=120, facecolors='none', zorder=10)    
plt.xlabel(iris_feature[0], fontsize=13)
plt.ylabel(iris_feature[1], fontsize=13)
plt.xlim(x1_min, x1_max)
plt.ylim(x2_min, x2_max)
plt.title(u'鸢尾花SVM特征分类', fontsize=16)
plt.grid(b=True, ls=':')
plt.tight_layout(pad=1.5)
plt.show()